# Generated by Django 6.0.1 on 2026-01-20 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cineboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cineboard', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cineboard/')),
                ('description', models.TextField()),
                ('type_cineboard', models.CharField(choices=[('Боевик', 'Боевик'), ('Драма', 'Драма'), ('Документальный', 'Документальный'), ('Триллер', 'Триллер')], default='Education', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], default='⭐⭐⭐⭐', max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_cineboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='cineboard.cineboard')),
            ],
        ),
    ]
