# Generated by Django 6.0.1 on 2026-01-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cineboard',
            name='type_cineboard',
            field=models.CharField(choices=[('Боевик', 'Боевик'), ('Драма', 'Драма'), ('Документальный', 'Документальный'), ('Триллер', 'Триллер')], default='Драма', max_length=100),
        ),
    ]
