# Generated by Django 6.0.1 on 2026-01-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineboard', '0002_alter_cineboard_type_cineboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cineboard',
            name='type_cineboard',
            field=models.CharField(choices=[('Боевик', 'Боевик'), ('Драма', 'Драма'), ('Документальный', 'Документальный'), ('Триллер', 'Триллер')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='marks',
            field=models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=100),
        ),
    ]
