# Generated by Django 6.0.1 on 2026-01-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineboard', '0004_film_genre_tag_remove_reviews_choice_cineboard_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-rating']},
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
