# Generated by Django 6.0.1 on 2026-01-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineboard', '0005_alter_film_options_alter_genre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='film',
            options={},
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
