# Generated by Django 6.0.1 on 2026-01-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineboard', '0006_remove_film_tags_alter_film_options_alter_genre_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='films/'),
        ),
    ]
