# Generated by Django 6.0.1 on 2026-01-20 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineboard', '0007_film_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_films', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='film',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
