# Generated by Django 6.0.1 on 2026-01-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineboard', '0008_film_likes_film_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
