# Generated by Django 6.0.1 on 2026-01-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='type_products',
            field=models.CharField(choices=[('JDM', 'JDM'), ('Supercar', 'Supercar'), ('Truck', 'Truck'), ('Dragster', 'Dragster')], default='Education', max_length=100),
        ),
    ]
