# Generated by Django 6.0.1 on 2026-01-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
